[package]

name = "handlebars"
version = "1.0.1"
authors = ["Ning Sun <sunng@pm.me>"]
description = "Handlebars templating implemented in Rust."
license = "MIT"
keywords = ["handlebars", "templating", "web"]
categories = ["template-engine"]
homepage = "https://github.com/sunng87/handlebars-rust"
repository = "https://github.com/sunng87/handlebars-rust"
documentation = "https://docs.rs/crate/handlebars/"
readme = "README.md"

[lib]

name = "handlebars"
path = "src/lib.rs"

[dependencies]

log = "^0.4.0"
quick-error = "^1.0.0"
pest = "^1.0.0"
pest_derive = "^1.0.7"
serde = "^1.0.0"
serde_json = "^1.0.0"
regex = "^1.0.0"
lazy_static = "^1.0.0"
walkdir = { version = "^2.1.4", optional = true }

[dev-dependencies]
env_logger = "^0.5.0"
maplit = "^1.0.0"
serde_derive = "^1.0.0"
tempfile = "^3.0.0"

[features]
dir_source = ["walkdir"]
default = ["dir_source"]
no_dir_source = []

[badges]
maintenance = { status = "actively-developed" }
