[package]

name = "handlebars"
version = "1.0.6-alpha.0"
authors = ["Ning Sun <sunng@pm.me>"]
description = "Handlebars templating implemented in Rust."
license = "MIT"
keywords = ["handlebars", "templating", "web"]
categories = ["template-engine"]
homepage = "https://github.com/sunng87/handlebars-rust"
repository = "https://github.com/sunng87/handlebars-rust"
documentation = "https://docs.rs/crate/handlebars/"
readme = "README.md"

[lib]

name = "handlebars"
path = "src/lib.rs"

[dependencies]

log = { version = "0.4.0", optional = true }
quick-error = "1.0.0"
pest = "1.0.0"
pest_derive = "1.0.8"
serde = "1.0.0"
serde_json = "1.0.0"
regex = "1.0.3"
lazy_static = "1.0.0"
walkdir = { version = "2.2.3", optional = true }

[dev-dependencies]
env_logger = "0.5.13"
maplit = "1.0.0"
serde_derive = "1.0.75"
tempfile = "3.0.0"

[features]
dir_source = ["walkdir"]
logging = ["log"]

default = ["dir_source", "logging"]

no_dir_source = ["logging"]
no_logging = ["dir_source"]

[badges]
maintenance = { status = "actively-developed" }
